import React from 'react';
import { BusinessPlan, CompanyDetails, FinancialSummaryData } from '../types.ts';

interface PrintSummaryProps {
  plan: BusinessPlan | null;
  summaries: FinancialSummaryData[];
  companyDetails: CompanyDetails | null;
}

const formatCurrency = (value: number) => {
  const options = {
    style: 'currency',
    currency: 'USD',
  };
  if (value < 0) {
    return `(${new Intl.NumberFormat('en-US', options).format(Math.abs(value))})`;
  }
  return new Intl.NumberFormat('en-US', options).format(value);
};

const formatNumber = (value: number) => {
    return new Intl.NumberFormat('en-US').format(Math.round(value));
}

const formatPercentage = (value: number) => {
    return `${value.toFixed(1)}%`;
}

export const PrintSummary: React.FC<PrintSummaryProps> = ({ plan, summaries, companyDetails }) => {
  if (!plan || summaries.length === 0) {
    return null;
  }

  const metrics = [
    { label: 'Total Revenue', key: 'totalRevenue', format: formatCurrency },
    { label: 'Total Variable Costs', key: 'totalVariableCosts', format: formatCurrency },
    { label: 'Gross Profit', key: 'grossProfit', format: formatCurrency, canBeNegative: true },
    { label: 'Gross Margin', key: 'grossMargin', format: formatPercentage, separator: true, canBeNegative: true },
    { label: 'Total Fixed Costs', key: 'totalFixedCosts', format: formatCurrency, separator: true },
    { label: 'Net Profit / Loss', key: 'netProfit', format: formatCurrency, canBeNegative: true },
    { label: 'Net Margin', key: 'netMargin', format: formatPercentage, separator: true, canBeNegative: true },
    { label: 'Break-Even Point (Units)', key: 'breakEvenUnits', format: formatNumber },
  ];

  return (
    <div className="p-10 bg-gray-50 font-sans">
      <header className="mb-10 text-center">
        {companyDetails?.logo && (
          <img src={companyDetails.logo} alt="Company Logo" className="mx-auto h-20 w-auto mb-6 object-contain" />
        )}
        <h1 className="text-4xl font-bold text-gray-800">{companyDetails?.name || plan.businessName}</h1>
        {companyDetails?.slogan && (
          <p className="text-lg text-gray-500 mt-2">{companyDetails.slogan}</p>
        )}
         {companyDetails?.address && (
          <p className="text-sm text-gray-400 mt-2">{companyDetails.address}</p>
        )}
        <p className="text-sm text-gray-400 mt-4">Multi-Year Financial Summary | Generated on: {new Date().toLocaleDateString()}</p>
      </header>
      <main className="bg-white rounded-xl shadow-lg p-1">
        <table className="w-full text-left">
          <thead>
            <tr>
              <th className="p-4 font-bold text-sm uppercase text-slate-500 tracking-wider">Metric</th>
              {plan.years.map((_, index) => (
                <th key={index} className="p-4 text-right font-bold text-sm uppercase text-slate-500 tracking-wider">
                  Year {index + 1}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {metrics.map((metric) => (
              <tr key={metric.key} className={`border-t ${metric.separator ? 'border-slate-300' : 'border-slate-100'}`}>
                <td className="p-4 font-semibold text-slate-700">{metric.label}</td>
                {summaries.map((summary, index) => {
                   const value = summary[metric.key as keyof FinancialSummaryData] as number;
                   const isNegative = metric.canBeNegative && value < 0;
                  return (
                  <td
                    key={index}
                    className={`p-4 text-right font-mono ${
                      isNegative
                        ? 'text-red-600 font-semibold'
                        : 'text-slate-900'
                    }`}
                  >
                    {metric.format(value)}
                  </td>
                )})}
              </tr>
            ))}
          </tbody>
        </table>
      </main>
      <footer className="mt-8 pt-4 text-center text-xs text-gray-400">
        <p>Generated by Business Plan Builder</p>
      </footer>
    </div>
  );
};